<?php

return [
  'icc_statuses' => [
    0 => null,
    1 => 'Draft',
    2 => 'Submitted',
    3 => 'Endorsed',
    4 => 'Approved',
  ],
  'badge_color' => [
    0 => null,
    1 => 'secondary',
    2 => 'warning',
    3 => 'info',
    4 => 'success',
  ],
  // 'new_user_statuses' => [
  //   0 => null,
  //   1 => 'New',
  //   2 => 'Approved',
  //   3 => 'Rejected',
  //   4 => 'Blocked',
  // ],
  // 'inquiry_statuses' => [
  //   0 => null,
  //   1 => 'New',
  //   2 => 'Replied',
  //   3 => 'Blocked',
  // ],
  // 'inquiry_statuses_color' => [
  //   0 => null,
  //   1 => 'info',
  //   2 => 'success',
  //   3 => 'danger',
  // ],
  'inquiry_statuses' => [
    0 => null,
    1 => 'New',
    2 => 'Read',
    3 => 'Replied',
    4 => 'Blocked',
  ],
  'inquiry_statuses_color' => [
    0 => null,
    1 => 'info',
    2 => 'secondary',
    3 => 'success',
    4 => 'danger',
  ],
  'email_automation_group_recipients' => [
    'agency_head' => [
      'head_firstname',
      'head_lastname',
      'head_designation',
      'head_email',
      'head_phone',
      'projects',
    ],
    'agency_staff' => [
      'firstname',
      'lastname',
      'designation',
      'email',
      'phone',
      'projects',
    ],
    'neda_pis' => [
      'firstname',
      'lastname',
      'designation',
      'email',
      'phone',
      'projects',
    ],
    'neda_other_ss' => [
      'firstname',
      'lastname',
      'designation',
      'email',
      'phone',
      'projects',
    ],
    'neda_admin' => [
      'firstname',
      'lastname',
      'designation',
      'email',
      'phone',
      'projects',
    ],
  ],
  'icc_submission_statuses' => [
    0 => null,
    1 => 'Draft',
    2 => 'Submitted',
    3 => 'Completeness Check',
    4 => 'Compliance Check',
  ],
  'icc_submission_statuses_color' => [
    0 => null,
    1 => 'secondary',
    2 => 'warning',
    3 => 'info',
    4 => 'success',
  ],


  'office_hours' => [
    'start' => [8, 0], // 1st array is for hour(24 hrs format), 2nd is for minutes
    'end' => [17, 0], // 1st array is for hour(24 hrs format), 2nd is for minutes
  ],
  'include_weekends' => false,
  'include_suspensions_holidays' => false,

  'icc_submission_custom_statuses' => [
    0 => null,
    1 => 'Rejected',
    2 => 'Draft',
    3 => 'For Revision(CPLT)',
    4 => 'For Review(CPLT)',
    5 => 'For Revision(CMPL)',
    6 => 'For Review(CMPL)',
    7 => 'Completed',
  ],

  'icc_submission_custom_statuses_color' => [
    '' => 'secondary',
    'Rejected' => 'danger',
    'Draft' => 'secondary',
    'For Revision(CPLT)' => 'purple',
    'For Review(CPLT)' => 'warning',
    'For Revision(CMPL)' => 'purple',
    'For Review(CMPL)' => 'info',
    'Completed' => 'success',
  ],

  'icc_attachment_statuses' => [
    0 => null,
    1 => 'Draft',
    2 => 'For Revision',
    3 => 'For Review(CPLT)',
    4 => 'Approved(CPLT)',
    5 => 'For Revision(CMPL)',
    6 => 'For Review(CMPL)',
    7 => 'Approved(CMPL)',
    8 => 'Rejected',
  ],

  'icc_attachment_statuses_color' => [
    0 => 'secondary',
    1 => 'secondary',
    2 => 'purple',
    3 => 'warning',
    4 => 'success',
    5 => 'purple',
    6 => 'info',
    7 => 'success',
    8 => 'danger',
  ],
  'spatial_coverage_types' => [
    0 => null,
    1 => 'Nationwide',
    2 => 'Interregional',
    3 => 'Region Specific',
    4 => 'Abroad',
  ],
  'agency_categories' => [
    'HEAD' => 'Head Agency',
    'ATT' => 'Attached Agency',
    'SUC' => 'State University and College',
    'GOCC' => 'Government-Owned or Controlled Corporation',
    'ATT_GOCC' => 'Attached GOCC',
  ],
  'registration_statuses' => [
    0 => null,
    1 => 'New',
    2 => 'Approved',
    3 => 'Rejected',
    4 => 'Blocked',
  ],
  'registration_statuses_color' => [
    0 => null,
    1 => 'info',
    2 => 'success',
    3 => 'warning',
    4 => 'danger',
  ],
  'new_funding_sources' => [
    ['id' => 1, 'name' => 'Locally Funded'],
    ['id' => 2, 'name' => 'ODA Loan'],
    ['id' => 5, 'name' => 'PPP'],
    ['id' => 6, 'name' => 'Others'],
  ],
];
