<?php

return [
    'predefined' => [
        'key' => 'uplift_measure_progress_tracking',
        'name' => 'UPLIFT Measure Progress Tracking Template',
        'description' => 'Standard UPLIFT measure progress tracking form structure.',
        'fields' => [
            [
                'label' => 'Duration / Status',
                'section' => null,
                'guide' => null,
                'value_type' => 'section',
                'options' => null,
                'column_size' => 12,
                'row_number' => 1,
                'order' => 0,
                'is_required' => 0,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Date Field',
                'section' => 'Duration / Status',
                'guide' => 'Indicate the official start date of implementation or launch. The date initiated should be reckoned from the onset of the energy-related disruption in the country, around March 3, 2026, rather than from the subsequent issuance of EO No. 110. For pre-existing programs, indicate the date when the program was expanded, repurposed, or applied to address the impact of the Middle East crisis.',
                'value_type' => 'date',
                'options' => null,
                'column_size' => 4,
                'row_number' => 1,
                'order' => 1,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Status',
                'section' => 'Duration / Status',
                'guide' => 'Select the current implementation status as of the reporting date: Ongoing, Completed, or Pending. If completed, indicate the date of completion.',
                'value_type' => 'select',
                'options' => ['Ongoing', 'Completed', 'Pending'],
                'column_size' => 4,
                'row_number' => 1,
                'order' => 2,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Outreach',
                'section' => null,
                'guide' => null,
                'value_type' => 'section',
                'options' => null,
                'column_size' => 12,
                'row_number' => 2,
                'order' => 0,
                'is_required' => 0,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Provinces and Cities/Municipalities Covered',
                'section' => 'Outreach',
                'guide' => 'List the provinces and cities or municipalities covered by the measure. Where feasible, reporting should go down to the province or city level rather than stopping at the regional level. For nationwide measures, write “Nationwide” and indicate available geographic breakdowns where applicable.',
                'value_type' => 'repeating_group',
                'options' => [
                    'columns' => [
                        ['id' => 'col_1779164369225_498535', 'label' => 'Coverage Type', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779165067446_374041', 'label' => 'Province', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779165070788_538633', 'label' => 'City/Municipality', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779165076988_812361', 'label' => 'Remarks', 'type' => 'text', 'source' => null],
                    ],
                ],
                'column_size' => 12,
                'row_number' => 2,
                'order' => 1,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Beneficiaries Sector/Group',
                'section' => 'Outreach',
                'guide' => 'Clearly identify the primary beneficiary group. Use disaggregated categories where applicable, instead of broad labels. For transport-related measures, specify the exact sub-sector and corresponding number of units, drivers, operators, or beneficiaries reached, as applicable.',
                'value_type' => 'repeating_group',
                'options' => [
                    'columns' => [
                        ['id' => 'col_1779164384164_639716', 'label' => 'Beneficiary Group', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779165089630_539510', 'label' => 'Number', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779337708514_123550', 'label' => 'Unit', 'type' => 'text', 'source' => null],
                    ],
                ],
                'column_size' => 12,
                'row_number' => 2,
                'order' => 4,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Exact Support Provided to Beneficiaries',
                'section' => 'Outreach',
                'guide' => 'Describe the assistance provided. For monetary support, indicate the amount and unit, such as PhP 5,000 per household. For non-monetary support, specify the nature of the support.',
                'value_type' => 'repeating_group',
                'options' => [
                    'columns' => [
                        ['id' => 'col_1779164385528_664274', 'label' => 'Support Type', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779165139550_748584', 'label' => 'Unit', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779165142330_703335', 'label' => 'Quantity / Value', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779165145178_98606', 'label' => 'Remarks', 'type' => 'text', 'source' => null],
                    ],
                ],
                'column_size' => 12,
                'row_number' => 2,
                'order' => 7,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Accomplishment',
                'section' => null,
                'guide' => null,
                'value_type' => 'section',
                'options' => null,
                'column_size' => 12,
                'row_number' => 3,
                'order' => 0,
                'is_required' => 0,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Total Number of Target Beneficiaries',
                'section' => 'Accomplishment',
                'guide' => 'Indicate the total number of intended beneficiaries. Always state the unit of measurement, such as persons, households, firms, drivers, operators, or units.',
                'value_type' => 'repeating_group',
                'options' => [
                    'columns' => [
                        ['id' => 'col_1779164512914_537896', 'label' => 'Name', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779168056044_759856', 'label' => 'Value', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779168061734_883942', 'label' => 'Remarks', 'type' => 'text', 'source' => null],
                    ],
                ],
                'column_size' => 12,
                'row_number' => 3,
                'order' => 1,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Total Number of Actual Beneficiaries as of Reporting Date',
                'section' => 'Accomplishment',
                'guide' => 'Provide the cumulative total number of actual beneficiaries reached as of the reporting date. Use the same unit of measurement as the target beneficiaries.',
                'value_type' => 'repeating_group',
                'options' => [
                    'columns' => [
                        ['id' => 'col_1779164513971_479612', 'label' => 'Beneficiary Group', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779168093616_534494', 'label' => 'Unit', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779168093969_818971', 'label' => 'Count', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779168094453_44648', 'label' => 'Remarks', 'type' => 'text', 'source' => null],
                    ],
                ],
                'column_size' => 12,
                'row_number' => 3,
                'order' => 4,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Other Accomplishments as of Reporting Date',
                'section' => 'Accomplishment',
                'guide' => 'Summarize key accomplishments or milestones not captured in the beneficiary count. Limit the entry to one to two sentences.',
                'value_type' => 'text',
                'options' => null,
                'column_size' => 12,
                'row_number' => 3,
                'order' => 7,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Issue Escalation',
                'section' => null,
                'guide' => null,
                'value_type' => 'section',
                'options' => null,
                'column_size' => 12,
                'row_number' => 4,
                'order' => 0,
                'is_required' => 0,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Issues / Bottlenecks',
                'section' => 'Issue Escalation',
                'guide' => 'Identify major implementation issues affecting progress, such as funding constraints, logistical issues, data validation concerns, procurement delays, operational gaps, coordination issues, or policy dependencies.',
                'value_type' => 'text',
                'options' => null,
                'column_size' => 4,
                'row_number' => 4,
                'order' => 1,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Action Needed from UPLIFT Committee / the President',
                'section' => 'Issue Escalation',
                'guide' => 'Specify the decision, policy guidance, inter-agency support, resource action, or escalation required from the UPLIFT Committee, the President, or other higher authority, as applicable. Do not include matters that can be resolved at the agency operating level.',
                'value_type' => 'text',
                'options' => null,
                'column_size' => 4,
                'row_number' => 4,
                'order' => 2,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Budget-related',
                'section' => null,
                'guide' => null,
                'value_type' => 'section',
                'options' => null,
                'column_size' => 12,
                'row_number' => 5,
                'order' => 0,
                'is_required' => 0,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Estimated Total Amount Needed',
                'section' => 'Budget-related',
                'guide' => 'Provide the estimated total funding requirement for the measure up to the applicable planning horizon, including the immediate and near-term implementation period where relevant.',
                'value_type' => 'decimal',
                'options' => null,
                'column_size' => 4,
                'row_number' => 5,
                'order' => 1,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Appropriations',
                'section' => 'Budget-related',
                'guide' => 'Indicate the total amount authorized or appropriated for the measure as of the reporting date.',
                'value_type' => 'decimal',
                'options' => null,
                'column_size' => 4,
                'row_number' => 5,
                'order' => 2,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Allotment Releases',
                'section' => 'Budget-related',
                'guide' => 'State the amount of allotments released as of the reporting date, such as SARO or other applicable allotment authority.',
                'value_type' => 'decimal',
                'options' => null,
                'column_size' => 4,
                'row_number' => 5,
                'order' => 3,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Obligations',
                'section' => 'Budget-related',
                'guide' => 'Indicate the cumulative amount obligated or committed as of the reporting date.',
                'value_type' => 'decimal',
                'options' => null,
                'column_size' => 4,
                'row_number' => 5,
                'order' => 4,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Disbursements',
                'section' => 'Budget-related',
                'guide' => 'Provide the cumulative amount actually disbursed or paid as of the reporting date. Disbursement figures should be consistent with reported obligations.',
                'value_type' => 'decimal',
                'options' => null,
                'column_size' => 4,
                'row_number' => 5,
                'order' => 5,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Supplemental / Additional Budget Needed',
                'section' => 'Budget-related',
                'guide' => 'Indicate the additional budget required to complete, continue, or scale up the measure, if applicable. If no additional budget is required, write “None.”',
                'value_type' => 'decimal',
                'options' => null,
                'column_size' => 4,
                'row_number' => 5,
                'order' => 6,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Additional Budget and Next Steps',
                'section' => null,
                'guide' => null,
                'value_type' => 'section',
                'options' => null,
                'column_size' => 12,
                'row_number' => 6,
                'order' => 0,
                'is_required' => 0,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Target Accomplishment with Additional Budget',
                'section' => 'Additional Budget and Next Steps',
                'guide' => null,
                'value_type' => 'repeating_group',
                'options' => [
                    'columns' => [
                        ['id' => 'col_1779164640338_86875', 'label' => 'Target Output', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779164659110_259570', 'label' => 'Quantity', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779164662048_250944', 'label' => 'Unit', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779164667638_516487', 'label' => 'Remarks', 'type' => 'text', 'source' => null],
                    ],
                ],
                'column_size' => 12,
                'row_number' => 6,
                'order' => 1,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Next Step',
                'section' => 'Additional Budget and Next Steps',
                'guide' => 'State the next implementation step or policy action, such as continued distribution, expansion of coverage, validation of beneficiaries, finalization of guidelines, release of funds, or proposed legislation.',
                'value_type' => 'text',
                'options' => null,
                'column_size' => 12,
                'row_number' => 6,
                'order' => 4,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Comms-related',
                'section' => null,
                'guide' => null,
                'value_type' => 'section',
                'options' => null,
                'column_size' => 12,
                'row_number' => 7,
                'order' => 0,
                'is_required' => 0,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Help for the Public',
                'section' => 'Comms-related',
                'guide' => 'Briefly explain how intended beneficiaries may access the assistance, including where to apply, who may qualify, what documents may be required, or where further information may be obtained.',
                'value_type' => 'text',
                'options' => null,
                'column_size' => 12,
                'row_number' => 7,
                'order' => 1,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Beneficiary Testimonial and Latest News',
                'section' => 'Comms-related',
                'guide' => 'Optional field. Include only verified testimonials, official updates, or significant developments that may support public communication.',
                'value_type' => 'repeating_group',
                'options' => [
                    'columns' => [
                        ['id' => 'col_1779332667371_534332', 'label' => 'Entry Type', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779332697726_880065', 'label' => 'Title / Summary', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779332703346_514026', 'label' => 'Source URL', 'type' => 'text', 'source' => null],
                        ['id' => 'col_1779332707065_424957', 'label' => 'Remarks', 'type' => 'text', 'source' => null],
                    ],
                ],
                'column_size' => 12,
                'row_number' => 7,
                'order' => 7,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Update Log and Certification',
                'section' => null,
                'guide' => null,
                'value_type' => 'section',
                'options' => null,
                'column_size' => 12,
                'row_number' => 8,
                'order' => 0,
                'is_required' => 0,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Updated by the Agency as of (DD/MM/YYYY)',
                'section' => 'Update Log and Certification',
                'guide' => 'Indicate the date up to which the data and figures are valid, using the format DD/MM/YYYY.',
                'value_type' => 'date',
                'options' => null,
                'column_size' => 4,
                'row_number' => 8,
                'order' => 1,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Prepared by',
                'section' => 'Update Log and Certification',
                'guide' => null,
                'value_type' => 'user_picker',
                'options' => null,
                'column_size' => 4,
                'row_number' => 8,
                'order' => 2,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
            [
                'label' => 'Review and cleared by',
                'section' => 'Update Log and Certification',
                'guide' => null,
                'value_type' => 'user_picker',
                'options' => null,
                'column_size' => 4,
                'row_number' => 8,
                'order' => 3,
                'is_required' => 1,
                'has_remarks' => 0,
                'status' => 1,
            ],
        ],
    ],
];
